export const data = [
  {
    id: 1,
    name: "Caleb Jones",
    role: "Data Anaylist",
    img: "https://images.pexels.com/photos/8371721/pexels-photo-8371721.jpeg?auto=compress&cs=tinysrgb&w=600",
    location: "New Orlins",
    message: "Update",
  },
  {
    id: 2,
    name: "John Doe",
    img: "https://images.pexels.com/photos/1008251/pexels-photo-1008251.jpeg?auto=compress&cs=tinysrgb&w=600",
    role: "Web Dev",
    message: "Update",
    location: "Los Angeles",
  },
  {
    id: 3,
    name: "Jane Smith",
    role: "Data Management",
    img: "https://images.pexels.com/photos/1096668/pexels-photo-1096668.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "Chicago",
  },
  {
    id: 4,
    name: "Johnny Gold",
    role: "IT Expert",
    img: "https://images.pexels.com/photos/9451242/pexels-photo-9451242.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "New York",
  },
  {
    id: 5,
    name: "Great Jhones",
    role: "Data Scientist",
    img: "https://images.pexels.com/photos/8382048/pexels-photo-8382048.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "Las Vagas",
  },
  {
    id: 6,
    name: "Barbie Becam",
    role: "Mobile Developer",
    img: "https://images.pexels.com/photos/2646841/pexels-photo-2646841.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "Silicon Valley",
  },
  {
    id: 7,
    name: "Divine Smith",
    role: "Data Management",
    img: "https://images.pexels.com/photos/3184407/pexels-photo-3184407.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "United States",
  },
  {
    id: 8,
    name: "Presley Queen",
    role: "CyberSecurity",
    img: "https://images.pexels.com/photos/4063861/pexels-photo-4063861.jpeg?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "Chicago",
  },
  {
    id: 9,
    name: "Sophie Debra",
    role: " Business Management",
    img: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&w=600",
    message: "Update",
    location: "Chelsea",
  },
];

export default data;
